name: jiffy_vi
description: Fork from Jiffy 3.0.1
version: 3.0.1
homepage: https://github.com/jama5262/jiffy
repository: https://github.com/jama5262/jiffy
issue_tracker: https://github.com/jama5262/jiffy/issues
documentation: https://github.com/jama5262/jiffy/tree/master/doc
author: forked by toannmdev<toannm.jsc@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  intl: ^0.16.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
  flutter_test:
    sdk: flutter
